### PR TITLE
added scroll to top feature

### PR DESCRIPTION
**Pull request by jay-2000**
## Thank you for your contribution to Bloody-Buddy 🤩🤩 

[GitHub license](LICENSE) Open Source Love  PRs Welcome

**Please mention the following in order to get PR merged**  🙌🏻🙌🏻 

1. Kind of change this PR introduce : New feature which includes a scroll to top button on bottom of the right side 
2. Issue it resolves :     #79 
3. GitHub Page Link : https://jay-2000.github.io/Blood-Buddy/
4. Description : with the help of this button if any visitor has scrolled the home page then this button will help to direct to start part of the webpage from top and **this button is located at bottom right side.**

Note: Do let me know if any changes are required from my side @2024-SANDHYA 
      Thank you looking forward to contribute more

image

### CODE REVIEW

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
Looks nice, just please add smooth scroll effect and hover effect too :)

**Comment by jay-2000** [comment]
> Looks nice, just please add smooth scroll effect and hover effect too :)

done please review and merge my PR

**Comment by 2024-SANDHYA** [comment]
please resolve merge conflicts @jay-2000

**Review by jay-2000 — COMMENTED** [review]
solved merge conflict

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
I think this happened by mistake @jay-2000  Please rectify the same.

image

**Comment by jay-2000** [comment]
> solved merge conflict

@2024-SANDHYA done please merge my PR

**Comment by jay-2000** [comment]
> I think this happened by mistake @jay-2000 Please rectify the same.
> 
> image

@2024-SANDHYA i guess somebody before my pr got into review they have made this problem so can you merge this pr we can create a new issue that footer problem

**Comment by jay-2000** [comment]
> > I think this happened by mistake @jay-2000 Please rectify the same.
> > image
> 
> @2024-SANDHYA i guess somebody before my pr got into review they have made this problem so can you merge this pr we can create a new issue for that footer problem

@2024-SANDHYA solved all merge conflicts please merge my PR ASAP to prevent more conflicts

**Review by jay-2000 — COMMENTED** [review]
@2024-SANDHYA done with merge conflicts

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
Please resolve this problem, it's only occurring in yours and not other PRs so I think you need to fix things from your end @jay-2000 

image

**Comment by jay-2000** [comment]
> Please resolve this problem, it's only occurring in yours and not other PRs so I think you need to fix things from your end @jay-2000
> 
> image



> Please resolve this problem, it's only occurring in yours and not other PRs so I think you need to fix things from your end @jay-2000
> 
> image

@2024-SANDHYA solved all problems due to merge conflicts now its proper you can merge my PR now
thank you i have solved merge conflict since this was the first time where i have face the merge conflicts and now i got the experience how to solve and prevent the conflicts looking forward to contribute more. 

this is how it looks now......
image

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
You've changed the alignment and colors too @jay-2000  Please don't change that. Restore it 

image

**Review by jay-2000 — COMMENTED** [review]
now i guess everything is proper and sorry for this problem @2024-SANDHYA

**Comment by 2024-SANDHYA** [comment]
Good Work !! @jay-2000

**Comment by jay-2000** [comment]
> Good Work !! @jay-2000

thank you

**Pull request merged**
