### PR TITLE
Added hover effect to  Register buttons

### PR DESCRIPTION
**Pull request by geetika005**
## Thank you for your contribution 🤩🤩 

[GitHub license](LICENSE) Open Source Love  PRs Welcome

**Please mention the following in order to get PR merged**  🙌🏻🙌🏻 

1. Kind of change this PR introduce : Hover effect is added to the create account and skip button and their font is also changed
2. Issue it resolves : #47  
3. Screenshots & GitHub Page Link :

### CODE REVIEW

**Comment by 2024-SANDHYA** [comment]
> ## Thank you for your contribution 🤩🤩
> 
> [GitHub license](LICENSE) Open Source Love PRs Welcome
> 
> **Please mention the following in order to get PR merged** 🙌🏻🙌🏻
> 
>     1. Kind of change this PR introduce : Hover effect is added to the create account and skip button and their font is also changed
> 
>     2. Issue it resolves : [register buttons hover #47](https://github.com/2024-SANDHYA/Blood-Buddy/issues/47)
> 
>     3. Screenshots & GitHub Page Link :
> 
> 
> 

Provide github page link

**Comment by geetika005** [comment]
https://geetika005.github.io/Blood-Buddy/

**Review by 2024-SANDHYA — COMMENTED** [review]
No changes are reflected.

**Comment by geetika005** [comment]
can you please tell how to create that link?

**Comment by 2024-SANDHYA** [comment]
> can you please tell how to create that link?

You have not made any changes in the code, so they are not reflected, link is okay

**Comment by geetika005** [comment]
Screenshot_2021-12-17-14-40-28-61_40deb401b9ffe8e1df2f1cc5ba480b12
Screenshot_2021-12-17-14-40-39-71_40deb401b9ffe8e1df2f1cc5ba480b12
Mam i had made changes in register.css file ,you can check my commits

**Comment by geetika005** [comment]
The changes are reflected in my side

**Comment by 2024-SANDHYA** [comment]
Please don't use these colors, use some contrast colors, you can refer to this to match the color contrast https://www.canva.com/colors/color-wheel/

**Comment by geetika005** [comment]
Please check

**Comment by 2024-SANDHYA** [comment]
A big no !! The colors do not look at all !! Both of them blue makes no sense with red and then the previous one too in the yellowish base. Please use some contrast knowledge maintain the theme

**Comment by geetika005** [comment]
on hovering create account

**Pull request merged**
