### PR TITLE
Made All the pages Responsive with navbar

### PR DESCRIPTION
**Pull request by ZaidKhan2002**
## Thank you for your contribution to Bloody-Buddy 🤩🤩 

[GitHub license](LICENSE) Open Source Love  PRs Welcome

**Please mention the following in order to get PR merged**  🙌🏻🙌🏻 

1. Kind of change this PR introduce : Made all the pages responsive with navbar
2. Issue it resolves : #77 
3. GitHub Page Link : https://zaidkhan2002.github.io/Blood-Buddy/

### CODE REVIEW

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
@ZaidKhan2002  In every page there's some error or another like some of them I've mentioned  here :

1. Don't change alignments and color : 
image

2. Tab view, the text is half visible 
Screenshot 2021-12-25 at 17-07-46 BLOOD BUDDY

3. Distorted Mobile View 
Screenshot 2021-12-25 at 17-07-38 BLOOD BUDDY

**Comment by ZaidKhan2002** [comment]
Ohh Actually I have not even changed single file/page regarding this still I'll fix this and commit changes. Actually If there is another PR made committed to main page then there is merge conflict and then we have to pull the changes and write our code again so maybe that time this happen. Anyways I am fixing this right away.

**Comment by ZaidKhan2002** [comment]
I have done the changes if anything more is required from my side do let me know @2024-SANDHYA

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
on index.html page :

1. You've paused the video in the background
2. Removed hover effects from register button
3. Alignment of register is wrong :
image

4. Here, the padding and margin needs to be checked
image

On donate page:

1. You made font size way too small, please don't play with this 
image

2. Nav bar is literally at the top, no padding or margin you've added, please restore it to previous one

image

3. In the tab view, see the navbar
image

4. In mobile view, the whole  thing is distorted, see the footer and also where's the main content is going, way too high
image
5. Hover effects on this in mobile view are looking bad, restore it to previous one please don't play with this 

image


Same you've done with get help page @ZaidKhan2002  No padding or margin and etc..

**Comment by ZaidKhan2002** [comment]
@2024-SANDHYA I don't know how these changes are happening like you can check the changes I've made by going to <a href="https://github.com/2024-SANDHYA/Blood-Buddy/pull/96/files">this</a> Here you can see I have not played/changed any one the things mentioned above regarding font size or hover effect or sizing etc etc. And also on my device video is playing perfectly navbar is fully responsive both in mobile and in tablet. Again I'll commit the requested changes by tomorrow and then you can check.

**Comment by 2024-SANDHYA** [comment]
No issues @ZaidKhan2002  Take your time. Sometimes margin padding happens by default too.

**Comment by ZaidKhan2002** [comment]
@2024-SANDHYA can you check now !!

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
Please resolve the merge conflicts @ZaidKhan2002

**Pull request closed without merging**
