### PR TITLE
changed_registration

### PR DESCRIPTION
**Pull request by keshav2508**
## Thank you for your contribution to Bloody-Buddy 🤩🤩 

[GitHub license](LICENSE) Open Source Love  PRs Welcome

**Please mention the following in order to get PR merged**  🙌🏻🙌🏻 

1. Kind of change this PR introduce : registration page ui
2. Issue it resolves : #98 
3. GitHub Page Link : https://keshav2508.github.io/Blood-Buddy/

### CODE REVIEW

**Comment by keshav2508** [comment]
Hey sandhya, I have created this new branch please go through , Thanks .

**Comment by 2024-SANDHYA** [comment]
Mention the issue it resolves not the closed pr @keshav2508

**Review by 2024-SANDHYA — COMMENTED** [review]
Everything is too clustered, the designs are overlapping and I am not liking it as well. I don't want to make it like this as of now @keshav2508

**Comment by keshav2508** [comment]
it takes time to update the github page please check now there is no overlaping
image
image
image
image
image

**Comment by keshav2508** [comment]
https://keshav2508.github.io/Blood-Buddy/

**Comment by keshav2508** [comment]
If it is still unsatisfactory please let me know

**Review by 2024-SANDHYA — COMMENTED** [review]
See @keshav2508 

image

The navbar too is way too clustered

**Comment by keshav2508** [comment]
okay i'll look into it , maybe it is happening because of different screen size, i'll make it general and get back to you.

**Pull request closed without merging**
