### PR TITLE
Improved Footer

### PR DESCRIPTION
**Pull request by MukadamSuha**
## Thank you for your contribution to Bloody-Buddy 🤩🤩 

[GitHub license](LICENSE) Open Source Love  PRs Welcome

**Please mention the following in order to get PR merged**  🙌🏻🙌🏻 
Improved the footer for website
#1

before footer
after footer

1. Kind of change this PR introduce #1
2. Issue it resolves : arranged the content and socials logo
3. GitHub Page Link : https://mukadamsuha.github.io/Blood-Buddy/

### CODE REVIEW

**Comment by 2024-SANDHYA** [comment]
Provide me the GitHub page link not the repo or code link @MukadamSuha

**Comment by MukadamSuha** [comment]
I have updated the  comment at github link.Even adding it here github page link:https://mukadamsuha.github.io/Blood-Buddy/

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
Please change the font to the previous ones. Also the height of the footer is way too much so tryna work on that too

**Comment by MukadamSuha** [comment]
ok will do

**Comment by MukadamSuha** [comment]
I have done the changes as you had asked

**Comment by 2024-SANDHYA** [comment]
Why have you done this now?   @MukadamSuha 

image

**Comment by MukadamSuha** [comment]
That might have been a mistake in code,sorry for chaos.Will fix it

**Pull request merged**
