### PR TITLE
Tip branch

### PR DESCRIPTION
**Pull request by Ritika122001**
## Thank you for your contribution to Bloody-Buddy 🤩🤩 

[GitHub license](LICENSE) Open Source Love  PRs Welcome

**Please mention the following in order to get PR merged**  🙌🏻🙌🏻 

1. Kind of change this PR introduce : Added the tips section to be followed before blood donation.
Screenshot (375)

2. Issue it resolves : #61 
3. GitHub Page Link : https://ritika122001.github.io/Blood-Buddy/

### CODE REVIEW

**Comment by Ritika122001** [comment]
Kindly Check !!

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
pull the lastest changes first @Ritika122001

**Comment by Ritika122001** [comment]
> pull the lastest changes first @Ritika122001

How to do this?

**Comment by 2024-SANDHYA** [comment]
> > pull the lastest changes first @Ritika122001
> 
> How to do this?

refer this  @Ritika122001 https://www.dataschool.io/how-to-contribute-on-github/

**Comment by Ritika122001** [comment]
Do I have to create a pull request again? Kindly Check.

**Comment by 2024-SANDHYA** [comment]
No @Ritika122001

**Comment by Ritika122001** [comment]
Kindly Check. Is it Working?

**Pull request closed without merging**
