### PR TITLE
Adding box Shadow under About us Section. #59

### LINKED ISSUE #59: Adding box Shadow under About us Section.
Under the About us Section, On hover with the transition effect I want to add Box Shadow it will more enhance the looks of cards.
Will you Assign this to me?

### PR DESCRIPTION
**Pull request by techwithbhavya**
1. Kind of change this PR introduce: On Hover, it will Transform the About-us Cards and also box-shadow effects shows at hovering. Similarly, the red border also adds in order to Resemble the theme of red related to Blood-Buddy.
2. Issue it resolves: #59 
3. Screenshots & GitHub Page Link: https://bhavyastar.github.io/Blood-Buddy/
 Screenshot of Problem:

145992785-99bce69e-cb5b-4d7f-b72a-162ed7b4aee5
 Solution of Problem:

145992882-93b15ad9-6d6d-4d86-876c-31f166c7792e

### CODE REVIEW

**Comment by bhavyastar** [comment]
Ma'am, Please Check this now. Now, I link the issue.

**Comment by 4bhishek10** [comment]
can I add borders to this card on hover

**Comment by 2024-SANDHYA** [comment]
No changes are visible @bhavyastar

**Comment by 2024-SANDHYA** [comment]
Any update on this, if not closing the PR @bhavyastar

**Pull request closed without merging**
