### PR TITLE
changed columns and hover in the websites index page

### PR DESCRIPTION
**Pull request by ssachis**
## Thank you for your contribution 🤩🤩 

[GitHub license](LICENSE) Open Source Love  PRs Welcome

**Please mention the following in order to get PR merged**  🙌🏻🙌🏻 

1. Kind of change this PR introduce :
2. Issue it resolves : 
3. Screenshots & GitHub Page Link :

### CODE REVIEW

**Comment by ssachis** [comment]
https://ssachis.github.io/Blood-Buddy/

**Comment by ssachis** [comment]
for UI improvement

**Comment by 2024-SANDHYA** [comment]
Looks sooo bad.

**Comment by ssachis** [comment]
Dont be rude, you could have simply closed the pr or say you didn't like the changes.

**Comment by 2024-SANDHYA** [comment]
> Dont be rude, you could have simply closed the pr or say you didn't like the changes.

I didn't mean it though, I was having a really bad day. I am so sorry, I  hope you'll understand @ssachis  :)

**Pull request closed without merging**
