### PR TITLE
Get  Help page is now responsive including navigation bar

### LINKED ISSUE #110: Modify Get Help page
I will make the page responsive and i will fix the navbar and currently by going to the get help page we can not see the connect with us form properly to do so we have to scroll ,that thing i will fix. thank you for your time.

### PR DESCRIPTION
**Pull request by SO1ee**
## Thank you for your contribution to Bloody-Buddy 🤩🤩 

[GitHub license](LICENSE) Open Source Love  PRs Welcome

1. Get help page is now completely responsive including navigation bar and the form is now completely visible at a glimpse
2. Issue it resolves : #110 
3. GitHub Page Link : https://so1ee.github.io/Blood-Buddy/

### CODE REVIEW

**Comment by SO1ee** [comment]
@2024-SANDHYA , Please check

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
Don't change navbar @SO1ee 
image

**Comment by SO1ee** [comment]
@2024-SANDHYA Navigation design is changed to it's earlier version and it's still responsive.

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
Font size for all the devices is same, change that @SO1ee . Also increase the width of send button.

**Comment by SO1ee** [comment]
@2024-SANDHYA font-size issue is fixed

**Comment by SO1ee** [comment]
@2024-SANDHYA ,Please check this PR

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
Make the get-help page navbar the same as existing one, it's still not the same. @SO1ee Also, do not tag me every now and then to check the PR, I get the notification even if u don't tag me.

**Comment by 2024-SANDHYA** [comment]
Been 22 days already,closing the PR

**Pull request closed without merging**
