### PR TITLE
Created Post A Blood Request Page and linked that with other pages

### PR DESCRIPTION
**Pull request by pritmanvar**
## Created "Post a Blood Request" Page

1. Kind of change this PR introduce : **Post A Blood Request Page**
I had created another page on which user will be redirected as he/she will click on Post a Blood Request.
In that page I had created a form so user can enter some details like name, blood group, address etc.

2. Issue it resolves : #31 
3. Screenshots & GitHub Page Link : [Link to the branch where I had performed Changes](https://github.com/pritmanvar/Blood-Buddy)
**Screen Shot :**
image

### CODE REVIEW

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
I don't want the branch link, but the GitHub page link

**Comment by pritmanvar** [comment]
Here ig github page link @2024-SANDHYA 
[github page](https://pritmanvar.github.io/Blood-Buddy/)

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
Don't fill the navbar with this huge heading of request blood. you can create something else but don't add this in navbar @pritmanvar

**Comment by pritmanvar** [comment]
@2024-SANDHYA i worked on your suggested changes. kindly check it again.
Here is a link of [github page](https://pritmanvar.github.io/Blood-Buddy/)

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
You've literally copy-pasted the exact code of get help form. Not acceptable.

**Comment by pritmanvar** [comment]
Okay.
Will work again

**Pull request closed without merging**
