### PR TITLE
About us section improvement

### LINKED ISSUE #7: About Us Section
Enhance the about us section which is currently like this : 

image

### PR DESCRIPTION
**Pull request by SO1ee**
1. Height issue on about us section is resolved and animation is added.
2. Issue it resolves : #7 
3. GitHub Page Link : https://so1ee.github.io/Blood-Buddy/

### CODE REVIEW

**Comment by SO1ee** [comment]
Hii! @2024-SANDHYA  with your guidance  i have solved conflicts and made this PR . thank you for your guidance . If possible please add SOW 21 and related  labels .

**Comment by 2024-SANDHYA** [comment]
@SO1ee Mention the issue it resolves and not the PR

**Comment by SO1ee** [comment]
Done!

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
Please add some spacing between all the 6 cards, it's looking a bit clustered.  @SO1ee 

image

**Comment by SO1ee** [comment]
Okay ! give half an hour.

**Pull request closed without merging**
