### PR TITLE
Updated Volunteers section with Grids

### PR DESCRIPTION
**Pull request by davyj123**
[GitHub license](LICENSE) Open Source Love  PRs Welcome

1. Kind of change this PR introduce :
    This pr contain changes related to the #4 Redesign the volunteer section.
     In this pr the volunteer section is redesigned.
2. Issue it resolves : 
    Prevoius UI contain tabular representation of volunteer section which is not so good according to modern Ui's.
    In this pr volunteer section is redesigned to modern flex based design with good looking tiles.
3. Screenshots & GitHub Page Link : 
Screenshot (158)

Changed To :- 

Screenshot (179)

Issue it resolves :- #4
Github Page Link :- https://davyj123.github.io/Blood-Buddy/

### CODE REVIEW

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
I don't think you've changed anything cuz I am seeing this, @davyj123 

image

**Comment by davyj123** [comment]
Done.

**Comment by davyj123** [comment]
that's my little mistake

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
https://user-images.githubusercontent.com/75671152/147677026-32a30415-95ed-42ca-8cb0-cd41483e6681.mp4

@davyj123

**Comment by davyj123** [comment]
ok mam

**Comment by davyj123** [comment]
mam actually working proper at my local repo

**Comment by davyj123** [comment]
Updated succesfully

**Comment by davyj123** [comment]
Not showing any scroll bar
Screenshot (180)

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
Fix these  @davyj123 : 
1.  image
2. Where's the spacing in b/w 'em:
image

3. Fix the footer:
image

**Comment by davyj123** [comment]
Done

**Comment by davyj123** [comment]
@2024-SANDHYA  done with all changes

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
@davyj123  This is original one :

image



This is where you messed up a bit :

image



Don't play with the hero section please.

**Comment by davyj123** [comment]
Mam it is already perfect
Screenshot (182)

**Comment by davyj123** [comment]
All things are done from myside now.

**Comment by davyj123** [comment]
I have decreased font size by 6px because it is making website irresponsive in mobile widths.

**Comment by davyj123** [comment]
Mam when will this pr will get merged

**Comment by 2024-SANDHYA** [comment]
@davyj123  Pull the latest changes from the repo. Seek help from mentors @davyj123

**Comment by davyj123** [comment]
I pulled the latest changes. Now what i have to do.

**Comment by davyj123** [comment]
Mam please guide me

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
The button is not like this, check the existing site and correct it accordingly  @davyj123 

image


Add the spacing between this 

image

**Comment by 2024-SANDHYA** [comment]
Also @davyj123 Pull and merge the latest changes from the repo, I can see you have not done anything

**Comment by davyj123** [comment]
Done with previous design of register button
Screenshot (199)

**Comment by davyj123** [comment]
Please Check it.

**Comment by 2024-SANDHYA** [comment]
> Fix these @davyj123 :
> 
>     1. image
> 
>     2. Where's the spacing in b/w 'em:
>        image
> 
>     3. Fix the footer:
>        image

@davyj123  You have not worked on the second issue.

**Comment by davyj123** [comment]
Done second one.

**Comment by davyj123** [comment]
Mam You have assigned me #114. Please tell me if i will make a github page link for that then this will expires or this will remain in working condition?

**Comment by 2024-SANDHYA** [comment]
> Mam You have assigned me #114. Please tell me if i will make a github page link for that then this will expires or this will remain in working condition?

Both will work ofc. @davyj123

**Comment by 2024-SANDHYA** [comment]
Pull the latest changes from the repo first @davyj123

**Comment by davyj123** [comment]
Alredy pulled

**Comment by davyj123** [comment]
Now please tell me this will get merged or any issues yet.

**Comment by 2024-SANDHYA** [comment]
Pull that again please, follow what I am saying @davyj123 Because recent changes are added to the code.

**Comment by davyj123** [comment]
I pulled again using fetch stream  then pulled to update my local repo and then repushed my changes to my branch.

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
Please resolve the merge conflicts @davyj123

**Comment by davyj123** [comment]
Now please help me in this pull request

**Pull request closed without merging**
