### PR TITLE
Redesigned th footer

### PR DESCRIPTION
**Pull request by Swati002**
## Thank you for your contribution to Bloody-Buddy 🤩🤩 

[GitHub license](LICENSE) Open Source Love  PRs Welcome

**Please mention the following in order to get PR merged**  🙌🏻🙌🏻 

1. Kind of change this PR introduce :
2. Issue it resolves : 
3. GitHub Page Link :

### CODE REVIEW

**Comment by Swati002** [comment]
I have redesigned the footer.

**Comment by Swati002** [comment]
I have redesigned the footer please look into it @2024-SANDHYA

**Comment by Swati002** [comment]
@2024-SANDHYA

**Comment by 2024-SANDHYA** [comment]
Already told you, I won't respond to those who are not following the PR template.

**Pull request closed without merging**
