### PR TITLE
Add Password Strength Feature On Register Page

### PR DESCRIPTION
**Pull request by phenyloder**
**Added New Feature**
Added a password strength checker on the register page. The bar below shows red for the weak passwords, yellow for the medium ones and green for strong passwords. The feature is added using JavaScript in the file Register.js .

Issue Solved: #34 

Link of Commits: https://github.com/phenyloder/Blood-Buddy/commit/c27520da54c27b9501aab0b31eff2cf062615e3e

Screenshot Of The Webpage (The password entered is strong and so it shows green colour)
ss

### CODE REVIEW

**Comment by 2024-SANDHYA** [comment]
> **Added New Feature** Added a password strength checker on the register page. The bar below shows red for the weak passwords, yellow for the medium ones and green for strong passwords. The feature is added using JavaScript in the file Register.js .
> 
> Issue Solved: #34
> 
> Link of Commits: [phenyloder@c27520d](https://github.com/phenyloder/Blood-Buddy/commit/c27520da54c27b9501aab0b31eff2cf062615e3e)
> 
> Screenshot Of The Webpage (The password entered is strong and so it shows green colour) ss

Not the link to the commits but the GitHub page link of the changes you've made.

**Comment by phenyloder** [comment]
Added New Feature
Added a password strength checker on the register page. The bar below shows red for the weak passwords, yellow for the medium ones and green for strong passwords. The feature is added using JavaScript in the file Register.js .

Issue Solved: #34 

GitHub Page Link : https://phenyloder.github.io/Blood-Buddy/Register.html

Screenshot Of The Webpage (The password entered is strong and so it shows green colour)
ss

**Comment by phenyloder** [comment]
@2024-SANDHYA Ma'am, Can you please review my PR.

**Review by 2024-SANDHYA — APPROVED** [review]
Great Job !! @phenyloder

**Pull request merged**
