### PR TITLE
About us section improvement #28

### PR DESCRIPTION
**Pull request by SO1ee**
…the card height issue is solved

## Thank you for your contribution 🤩🤩 

[GitHub license](LICENSE) Open Source Love  PRs Welcome

**Please mention the following in order to get PR merged**  🙌🏻🙌🏻 

1. Kind of change this PR introduce :
2. Issue it resolves : 
3. Screenshots & GitHub Page Link :

### CODE REVIEW

**Comment by 2024-SANDHYA** [comment]
@SO1ee  Create issues first, then the PR, follow the PR template. Resolve the merge conflicts.

**Comment by SO1ee** [comment]
Okay . I am trying to solve the conflicts

**Comment by 2024-SANDHYA** [comment]
> !. It will only change the about us section 2.It fixed the height issue of the Network card on about us section and for every card on the about us section i have added animation . 3.https://github.com/SO1ee/Blood-Buddy screenshoot

Don't provide the link for the forked repo, but the GitHub page of this repo forked from your end. @SO1ee

**Comment by SO1ee** [comment]
Okay

**Comment by SO1ee** [comment]
1. It will only change the about us section
2.It fixed the height issue of the Network card on about us section and for every card on the about us section i have added animation .
3.https://github.com/2024-SANDHYA/Blood-Buddy
screenshoot

**Comment by SO1ee** [comment]
If any modification is needed please let me know.

**Comment by 2024-SANDHYA** [comment]
> If any modification is needed please let me know.

@SO1ee Neither I  want the repo link nor do I want the link of the existing website that's in the repo,  but the link for the changes that you made, so provide the GitHub page link for the changes that you have made.

**Comment by SO1ee** [comment]
oh! now i have got it

**Comment by SO1ee** [comment]
1. It will only change the about us section
2.It fixed the height issue of the Network card on about us section and for every card on the about us section i have added animation .
3.https://so1ee.github.io/Blood-Buddy/
screenshoot

**Comment by 2024-SANDHYA** [comment]
@SO1ee  Please make all three even.


image

**Comment by SO1ee** [comment]
It is even at my end 
Screenshot2

**Comment by SO1ee** [comment]
Conflicts resolved

**Comment by 2024-SANDHYA** [comment]
It's not @SO1ee  😅 

image

**Comment by SO1ee** [comment]
Hey ! Could you please guide me how to solve this conflict?

**Comment by 2024-SANDHYA** [comment]
@SO1ee  refer this https://www.atlassian.com/git/tutorials/using-branches/merge-conflicts

**Pull request closed without merging**
