### PR TITLE
Made donate page Responsive #2

### PR DESCRIPTION
**Pull request by devxprite**
#2  I made [Donate Page](https://2024-sandhya.github.io/Blood-Buddy/donate.html) responsive and improve some UI for mobile devices.

- [Current Page](https://2024-sandhya.github.io/Blood-Buddy/donate.html)
- [New Page](https://7orp3do.github.io/Blood-Buddy/donate.html)

### CODE REVIEW

**Comment by 7ORP3DO** [comment]
Hey @2024-SANDHYA , why this request was not merged when I have made its nav bar as reponsive as HomePage. 

At least tell the reason for not merging this Request.😐

**Comment by 2024-SANDHYA** [comment]
> Hey @2024-SANDHYA , why this request was not merged when I have made its nav bar as reponsive as HomePage.
> 
> At least tell the reason for not merging this Request.😐

Issue was never assigned to you.

**Comment by 7ORP3DO** [comment]
Nope, you assigned me on #2 when i  open #68. 🙂

**Comment by 2024-SANDHYA** [comment]
> Nope, you assigned me on #2 when i open #68. 🙂

Make whole website responsive then, not a page right

**Comment by 7ORP3DO** [comment]
Ok it means if you have 10 pages in your website then I have to make all those pages responsive and submit them in a single Pull Request at once and if  we submit PR for a single page then it will got rejected. Right?

So why #13 got merged.

**Comment by 7ORP3DO** [comment]
I don't know why you are doing this. I wasted my 1.5 hour on this PR. But you rejected this without any proper reason and review.

just lock this conversation, now I won't respond to this issue! 😓

**Comment by 2024-SANDHYA** [comment]
@7ORP3DO  Don't change the navbar, restore the previous one

**Pull request closed without merging**
