### PR TITLE
modified index.html and index.css

### PR DESCRIPTION
**Pull request by Swati002**
## Thank you for your contribution to Bloody-Buddy 🤩🤩 

[GitHub license](LICENSE) Open Source Love  PRs Welcome

**Please mention the following in order to get PR merged**  🙌🏻🙌🏻 

1. Kind of change this PR introduce: Improved the responsiveness of social icons in the footer and decrease the transition effect in the vertical direction so it is not covering the text above the social icons.
2. Issue it resolves :  #101 
3. GitHub Page Link :   https://swati002.github.io/Blood-Buddy/

### CODE REVIEW

**Comment by Swati002** [comment]
#101 Issue resolved. please check! @2024-SANDHYA

**Review by 2024-SANDHYA — COMMENTED** [review]
Can you mention what changes have you done? @Swati002  Because in the code I can only see you've added spaces or removed them between the lines in the code that's all !!

**Comment by Swati002** [comment]
> Can you mention what changes have you done? @Swati002 Because in the code I can only see you've added spaces or removed them between the lines in the code that's all !!

In footer social icons and 2021 © All rights reserved. were not responsive. I write media queries to make it responsive.

**Comment by Swati002** [comment]
@2024-SANDHYA In footer social icons and 2021 © All rights reserved. were not responsive. I write media queries to make it responsive.

**Comment by Swati002** [comment]
@2024-SANDHYA Please check!

**Review by 2024-SANDHYA — COMMENTED** [review]
The footer was responsive from the beginning, in the code, I can see you've removed and added the same things again. @Swati002

**Pull request closed without merging**
