### PR TITLE
changes_in_registration

### PR DESCRIPTION
**Pull request by keshav2508**
## Thank you for your contribution to Bloody-Buddy 🤩🤩 

[GitHub license](LICENSE) Open Source Love  PRs Welcome

**Please mention the following in order to get PR merged**  🙌🏻🙌🏻 

1. Kind of change this PR introduce :  changes in registration page
2. Issue it resolves : #97
3. GitHub Page Link : https://github.com/keshav2508/Blood-Buddy

### CODE REVIEW

**Comment by 2024-SANDHYA** [comment]
@keshav2508  Provide me GitHub page link, not the link of forked repo.

**Comment by keshav2508** [comment]
https://keshav2508.github.io/Blood-Buddy/

i dont know why it still shows the previous registration page but i have made changes 
image

**Comment by keshav2508** [comment]
https://keshav2508.github.io/Blood-Buddy/

**Comment by keshav2508** [comment]
do you want me to do any more changes??

**Comment by keshav2508** [comment]
please reply

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
Resolve the merge conflicts @keshav2508

**Pull request closed without merging**
