### PR TITLE
homepage view, social media animation in footer

### PR DESCRIPTION
**Pull request by bug17**
## Thank you for your contribution to Bloody-Buddy 🤩🤩 

[GitHub license](LICENSE) Open Source Love  PRs Welcome

**Please mention the following in order to get PR merged**  🙌🏻🙌🏻 
1-Homepage view 
2- footer social media handle pop up on focusing

Screenshot (38)
Screenshot (39)

1. Kind of change this PR introduce : Homepage and Footer
2. Issue it resolves :  better UI, responsiveness on devices like mobile phones.
3. GitHub Page Link : https://bug17.github.io/Blood-Buddy/

### CODE REVIEW

**Comment by 2024-SANDHYA** [comment]
Mention the issue number it resolves @bug17

**Comment by bug17** [comment]
Where can I get that? Also, I have contributed to make the UI better. I
have not done things related to the issue.

**Comment by bug17** [comment]
> 1. Mention the issue number it resolves @bug17
> 2. I don't want forked repo link but the GitHub page link

Sorry for the inconvenience , now I have edit the link you can check github page link.

**Comment by bug17** [comment]
> 1. Mention the issue number it resolves @bug17
> 2. I don't want forked repo link but the GitHub page link

I have updated github page link , Now you can check !

**Pull request merged**
