### PR TITLE
Issue #130 fixed plus added more functionality to the buttons.

### LINKED ISSUE #130: Volunteer page alignment
Align all the points properly. Right now it is like :

image

### PR DESCRIPTION
**Pull request by impranavtg**
## Thank you for your contribution to Bloody-Buddy 🤩🤩 

[GitHub license](LICENSE) Open Source Love  PRs Welcome

**Please mention the following in order to get PR merged**  🙌🏻🙌🏻 

1. Kind of change this PR introduce:  Issue #130 fixed plus added more functionality to the buttons. Now the buttons of the navigation bar redirect the user to the desired section of the home page. (example: If a user is on the Donate.html page and clicks on the 'About' button on the nav bar then it redirects to the About us section in the index.html page. Implemented for all buttons).
2. Issue it resolves:  #130 
3. GitHub Page Link:  https://impranavtg.github.io/Blood-Buddy/
issue130

### CODE REVIEW

**Review by 2024-SANDHYA — APPROVED** [review]

**Comment by impranavtg** [comment]
Hey @2024-SANDHYA I have a query. My ID is not listed in your project (no.48) but Your project ID (48) is listed in front of my name(no.685 Pranav Tyagi) in the Participants list.
https://docs.google.com/spreadsheets/d/1SX9FubA-n1ag_0n4WmzMXd6rq5lrkFmaAWl8fhHvTWM/edit#gid=0
Can you tell me why? Do I have to do something? or You will update this?

**Comment by 2024-SANDHYA** [comment]
> Hey @2024-SANDHYA I have a query. My ID is not listed in your project (no.48) but Your project ID (48) is listed in front of my name(no.685 Pranav Tyagi) in the Participants list. https://docs.google.com/spreadsheets/d/1SX9FubA-n1ag_0n4WmzMXd6rq5lrkFmaAWl8fhHvTWM/edit#gid=0 Can you tell me why? Do I have to do something? or You will update this?

I do not have idea about this, please ask SWOC Team @impranavtg

**Comment by impranavtg** [comment]
> > Hey @2024-SANDHYA I have a query. My ID is not listed in your project (no.48) but Your project ID (48) is listed in front of my name(no.685 Pranav Tyagi) in the Participants list. https://docs.google.com/spreadsheets/d/1SX9FubA-n1ag_0n4WmzMXd6rq5lrkFmaAWl8fhHvTWM/edit#gid=0 Can you tell me why? Do I have to do something? or You will update this?
> 
> I do not have idea about this, please ask SWOC Team @impranavtg

Okay Thanks

**Comment by impranavtg** [comment]
Hey @2024-SANDHYA, SWOC Mentor said that you have to add my ID to your Project sheet(no. 48). So for that, I have to comment my id on your project sheet. And I have already done that. So please resolve that comment and add my ID (685) to your sheet. Sorry for the inconvenience.
Regards
Pranav Tyagi

**Comment by 2024-SANDHYA** [comment]
> 685

Done @impranavtg

**Comment by impranavtg** [comment]
> > 685
> 
> Done @impranavtg

Thank You

**Comment by impranavtg** [comment]
Hey @2024-SANDHYA, You can use https://formspark.io/ this service to get user form data directly to your email id without using the backend. Just a suggestion, Because I can't create an issue for this. Hope it helps.

**Pull request merged**
