### PR TITLE
added transition effect in about and volunteer section

### PR DESCRIPTION
**Pull request by suyogkokaje**
## Thank you for your contribution 🤩🤩 

[GitHub license](LICENSE) Open Source Love  PRs Welcome

**Please mention the following in order to get PR merged**  🙌🏻🙌🏻 

1. Kind of change this PR introduce :
     This is PR is regarding enhancement in frontend. I have added fade-up transition effect to cards in about section and fade-right and fade-left effects to the name of volunteers in volunteer section.

2. Issue it resolves : 
    It resolve the issue number 29

3. Screenshots & GitHub Page Link : 
    It can't be shown through the screenshot as it is transition effect. 
    Here is the link of the github page to see the transition effects
<a href="https://suyogkokaje.github.io/Blood-Buddy-Changes/">https://suyogkokaje.github.io/Blood-Buddy-Changes/</a>

### CODE REVIEW

**Comment by 2024-SANDHYA** [comment]
> ## Thank you for your contribution 🤩🤩
> 
> [GitHub license](LICENSE) Open Source Love PRs Welcome
> 
> **Please mention the following in order to get PR merged** 🙌🏻🙌🏻
> 
>     1. Kind of change this PR introduce :
>        This is PR is regarding enhancement in frontend. I have added fade-up transition effect to cards in about section and fade-right and fade-left effects to the name of volunteers in volunteer section.
> 
>     2. Issue it resolves :
>        It resolve the issue number 29
> 
>     3. Screenshots & GitHub Page Link :
>        It can't be shown through the screenshot as it is transition effect.

Resolve the merge conflicts & provide GitHub page links for the changes you've made.

**Comment by suyogkokaje** [comment]
@2024-SANDHYA I have resolved the conflicts and updated my comment with github page link where you can preview the changes which I've made.

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
@suyogkokaje  looks good, just keep the effects on the about section and remove the newly added effects from volunteers. In the volunteer, section keep it as it was earlier

**Comment by suyogkokaje** [comment]
@2024-SANDHYA Thank you for suggestion. I have made suggested changes. Please have a look.

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
If you can make this even @suyogkokaje 

image

**Comment by suyogkokaje** [comment]
@2024-SANDHYA I have made all the cards of same size and also aligned them properly. Please have a look.

**Comment by suyogkokaje** [comment]
Hello @2024-SANDHYA please have a look.

**Comment by suyogkokaje** [comment]
Hello @2024-SANDHYA please have a look

**Comment by 2024-SANDHYA** [comment]
Resolve merge conflicts @suyogkokaje

**Comment by suyogkokaje** [comment]
Thanks for reminding @2024-SANDHYA. Actually I am going to close this PR as I am not continuing with your project in SWoC.

**Pull request closed without merging**
