### PR TITLE
The alignment of the social icons in the footer has been made right!

### PR DESCRIPTION
**Pull request by Kunal0220**
1. Kind of change this PR introduce :BugFix - the footer had the social icons not properly aligned , correction made
2. Issue it resolves : #116 
3. GitHub Page Link : https://github.com/2024-SANDHYA/Blood-Buddy/issues/116

Screenshot 2022-01-12 at 8 20 19 PM

### CODE REVIEW

**Comment by Kunal0220** [comment]
Here you go ma'am: https://github.com/2024-SANDHYA/Blood-Buddy/issues/116

**Comment by Kunal0220** [comment]
If I am not wrong , you were asking the link for the GitHub page of the issue , right?

**Comment by 2024-SANDHYA** [comment]
> If I am not wrong , you were asking the link for the GitHub page of the issue , right?

You are wrong, I am asking the GitHub page link, it has nothing to do with the issue @Kunal0220

**Comment by Kunal0220** [comment]
1. https://kunal0220.github.io/Blood-Buddy/
2. https://kunal0220.github.io/Blood-Buddy/donate.html
3. https://kunal0220.github.io/Blood-Buddy/help.html

**Review by 2024-SANDHYA — APPROVED** [review]

**Pull request merged**
