### PR TITLE
#4 - Redesigned the volunteer section with responsive grids.

### PR DESCRIPTION
**Pull request by davyj123**
[GitHub license](LICENSE) Open Source Love  PRs Welcome

1. Kind of change this PR introduce :
    This pr contain changes related to the #4 Redesign the volunteer section.
     In this pr the volunteer section is redesigned.
2. Issue it resolves : 
    Prevoius UI contain tabular representation of volunteer section which is not so good according to modern Ui's.
    In this pr volunteer section is redesigned to modern flex based design with good looking tiles.
3. Screenshots & GitHub Page Link : 
Screenshot (158)

Changed To :- 

Screenshot (159)

Issue it resolves :- #4
GIthub Page link :- https://davyj123.github.io/Blood-Buddy/

### CODE REVIEW

**Comment by davyj123** [comment]
When will the pr will get merged

**Comment by davyj123** [comment]
@2024-SANDHYA Check my pr

**Comment by davyj123** [comment]
@2024-SANDHYA  please check my pr

**Comment by davyj123** [comment]
is it mergeable or any issue

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
Looks okayish !! If you can add some CSS effects on the card

**Comment by davyj123** [comment]
if you want to add more changes I will add those also.

**Comment by 2024-SANDHYA** [comment]
> if you want to add more changes I will add those also.
 
Provide me the GitHub page link to track the changes. @davyj123

**Comment by davyj123** [comment]
Mam could you please tell about the github page link that i am supposed to provide.

**Comment by 2024-SANDHYA** [comment]
> Mam could you please tell about the github page link that i am supposed to provide.

Ask the mentors on discord how to create github page

**Comment by davyj123** [comment]
@2024-SANDHYA  mam please help me I am not getting any reference about github page link. I have also posted in SWOC Discord server but didn't get any response from mentors, also I don't know who is my mentor

**Comment by davyj123** [comment]
mam please tell me that I have to make github page link for my forked repo

**Comment by davyj123** [comment]
Mam please guide me

**Review by 2024-SANDHYA — COMMENTED** [review]
You can refer this : https://stackoverflow.com/questions/51114264/setting-up-github-pages-from-a-forked-repo @davyj123

**Comment by davyj123** [comment]
Ok mam try to fix changes as soon as possible

**Comment by 2024-SANDHYA** [comment]
> Ok mam try to fix changes as soon as possible

Any update on this ? if not, I'll close it then. @davyj123

**Comment by davyj123** [comment]
Will send a pr tomorrow with changes

**Comment by 2024-SANDHYA** [comment]
> Will send a pr tomorrow with changes

okay

**Comment by davyj123** [comment]
is it ok I have added my github id in pr.

**Review by 2024-SANDHYA — COMMENTED** [review]
What am I gonna do with your GitHub ID? Provide me the GitHub page link, If you don't know how to do that, please check discord. I've already dropped a video on this.  @davyj123

**Comment by davyj123** [comment]
Mam could you please tell in which channel you have already sent the video.

**Comment by 2024-SANDHYA** [comment]
> Mam could you please tell in which channel you have already sent the video.

Ofc the private channels of this project. @davyj123

**Comment by davyj123** [comment]
Mam soory for disturbance. I was busy in my exams. Please tell me how to join private channel of this project because i am not getting that channel and also when i an trying to dm you on discoed. I can't send messages.

**Comment by 2024-SANDHYA** [comment]
> Mam soory for disturbance. I was busy in my exams. Please tell me how to join private channel of this project because i am not getting that channel and also when i am trying to dm you on discord. I can't send messages to you.

I am so sorry @davyj123  Ask SWOC team I can't help in this case. Try DMing me now

**Comment by davyj123** [comment]
Mam could you please share the video link for now.

**Comment by davyj123** [comment]
Edited the pr with github page link

**Comment by 2024-SANDHYA** [comment]
Please resolve the merge conflicts @davyj123

**Comment by davyj123** [comment]
Mam I have sent a new pull request with id #100. Please check it

**Comment by davyj123** [comment]
I think these conflicts are coming because many changes are happened in the repo and my code is too old.
So i am sending a new pr with updated project.

**Comment by 2024-SANDHYA** [comment]
> I think these conflicts are coming because many changes are happened in the repo and my code is too old. So i am sending a new pr with updated project.

You could have solved them instead of creating a new PR @davyj123

**Pull request closed without merging**
