### PR TITLE
Issue-91 Logo resized & hover effect implemented

### PR DESCRIPTION
**Pull request by greyjedi7**
## Thank you for your contribution to Bloody-Buddy 🤩🤩 

[GitHub license](LICENSE) Open Source Love  PRs Welcome

**Please mention the following in order to get PR merged**  🙌🏻🙌🏻 

1. Kind of change this PR introduce : Logo Resizing and Hover Effect on Logo
2. Issue it resolves : #91 
3. GitHub Page Link : https://greyjedi7.github.io/Blood-Buddy/

Blood-Buddy-Logo-Size
Screenshot from 2021-12-24 10-35-25

### CODE REVIEW

**Comment by 2024-SANDHYA** [comment]
Provide me GitHub page link & not the link of forked repo. @greyjedi7

**Comment by greyjedi7** [comment]
I'm Sry I don't understand the term "github page link" as I'm new to PR. Can you describe what does github page means? Is it the issue link?

**Comment by 2024-SANDHYA** [comment]
> I'm Sry I don't understand the term "github page link" as I'm new to PR. Can you describe what does github page means? Is it the issue link? @2024-SANDHYA

@greyjedi7 No issues, this may help you : https://docs.github.com/en/pages/quickstart

**Comment by greyjedi7** [comment]
@2024-SANDHYA, I've updated my Github page. Thanks :)

**Comment by 2024-SANDHYA** [comment]
@greyjedi7  No you haven't. You've provided me a readme link, this :

image

**Comment by greyjedi7** [comment]
> @greyjedi7 No you haven't. You've provided me a readme link, this :
> 
> image

Sry! Kindly check now. I've changed it

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
Change the logo size for other pages too and not just index.html. Also, remove hover effects I am not liking it. Rest is nice @greyjedi7

**Comment by greyjedi7** [comment]
@2024-SANDHYA, I've updated the rest of the pages and removed the hover effects. Kindly, check now

**Review by 2024-SANDHYA — APPROVED** [review]

**Pull request merged**
