### PR TITLE
added colorful heading 

### PR DESCRIPTION
**Pull request by DPR-4**
## Thank you for your contribution to Bloody-Buddy 🤩🤩 

[GitHub license](LICENSE) Open Source Love  PRs Welcome

**Please mention the following in order to get PR merged**  🙌🏻🙌🏻 

Add colorful heading to the "what is all about this" and "Our super heroes" and also provide some cool effects

## Thank you for your contribution to Bloody-Buddy 🤩🤩 

[GitHub license](LICENSE) Open Source Love  PRs Welcome

**Please mention the following in order to get PR merged**  🙌🏻🙌🏻 

1. Kind of change this PR introduce : Add colorful heading
2. Issue it resolves : heading look more attractive than previous  
3. Screenshots & GitHub Page Link : https://dpr-4.github.io/
 here is screenshot 
Screenshot (357)
Screenshot (358)
Screenshot (359)
Screenshot (360)

### CODE REVIEW

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
Please provide the GitHub page link not the link of the forked repo.

**Comment by DPR-4** [comment]
which link I need to provide or create new repo and push the file to that new repo ,sorry I don't have experience in contribution

**Review by 2024-SANDHYA — COMMENTED** [review]
You may refer this : https://docs.github.com/en/pages/quickstart

**Comment by DPR-4** [comment]
https://dpr-4.github.io/
hey I did it as per that article

**Comment by DPR-4** [comment]
https://dpr-4.github.io/
hey I did it as per article

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
Well, I can't see anything colorful here @DPR-4 

image

**Comment by DPR-4** [comment]
actually I gave the colorful and some effect to "WHAT IS THIS ALL ABOUT ?" and "OUR SUPER HEROES"  for this heading I provided 
in screenshot you can clearly see it 
hope it will make website more interesting 
here is link : https://dpr-4.github.io/
Screenshot (358)

Screenshot (360)

**Review by 2024-SANDHYA — COMMENTED** [review]
Yeah, that is visible but the hero section appears to be blank.

**Comment by DPR-4** [comment]
ok and can I leave rest of part as it is and add colorful heading to "start saving life" with large font size and  "WHAT IS THIS ALL ABOUT ?"

**Comment by DPR-4** [comment]
hey I did changes and added cool effect button 
link:https://dpr-4.github.io/
and screenshot
Screenshot (370)

**Review by 2024-SANDHYA — COMMENTED** [review]
Well thank you so very much for the contribution, but I am not really liking it. But I must say great efforts. @DPR-4  😄

**Pull request closed without merging**
