### PR TITLE
logo design

### LINKED ISSUE #18: Redesign a good logo for the website
Create a logo inspired by the theme of the project and swap it with the existing one.

### PR DESCRIPTION
**Pull request by Aditidubey223**
## Thank you for your contribution to Bloody-Buddy 🤩🤩 

[GitHub license](LICENSE) Open Source Love  PRs Welcome

**Please mention the following in order to get PR merged**  🙌🏻🙌🏻 
  logo design
 #18 
 
pdf name " blood buddy logo redesign "

1. Kind of change this PR introduce :
2. Issue it resolves : #18  logo redesign
3. GitHub Page Link : 
https://github.com/Aditidubey223

### CODE REVIEW

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
@Aditidubey223  Provide GitHub page link and not the link of your GitHub profile. Follow the PR template, if you want the PR to get accepted.

**Comment by Aditidubey223** [comment]
I redesign  20 logos please select one of them so I can update it on  site and create the github page link here is the design of logos
https://www.canva.com/design/DAE2qxE-y-Q/9K2MYdfvi8NiRl5lY_j6vA/edit

github page link -https://aditidubey223.github.io/Blood-Buddy/

**Comment by Aditidubey223** [comment]
I created redesign 20 logos" https://www.canva.com/design/DAE2qxE-y-Q/9K2MYdfvi8NiRl5lY_j6vA/edit " so I can update on 
the site and create the github page link'

https://aditidubey223.github.io/Blood-Buddy/

**Comment by 2024-SANDHYA** [comment]
This looks okay, just keep this logo @Aditidubey223 

image

**Comment by Aditidubey223** [comment]
link of  github page :- https://aditidubey223.github.io/Blood-Buddy/

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
@Aditidubey223 Pathetic alignment

image

**Pull request closed without merging**
